### PR TITLE
Use generic operator

### LINKED ISSUE #586: `test_io.py` test is not running
It seems the `test_io.py` test is not running because it has not been added to the `test_all.py` script. 

Even when I run the script locally, it seems to be failing with some assertion errors. 

@kaiyingshan Could you please look into this?

### PR DESCRIPTION
**Pull request by kaiyingshan**
fixes #586 among other things

### CODE REVIEW

**Comment by nirandaperera** [comment]
@kaiyingshan this failure is in GCylon. Could you please check that as well?

File: cpp/src/cylon/table.cpp [hunk 1]
```diff
@@ -1469,19 +1467,28 @@ Status Equals(const std::shared_ptr<cylon::Table> &a, const std::shared_ptr<cylo
...
+  std::vector<std::shared_ptr<cylon::Column>> output;
+
+  RETURN_CYLON_STATUS_IF_FAILED(
+      a->GetContext()->GetCommunicator()->Allgather(num_row_col, &output));
+
+  for (auto col : output) {
+    auto temp = std::static_pointer_cast<arrow::Int64Scalar>(
+        col->data()->GetScalar(0).ValueOrDie());
+    rows_per_partition.push_back(temp->value);
+  }
```
Comment (nirandaperera) [inline cpp/src/cylon/table.cpp:1491]: I think you should've used the `Scalar` all-gather here. 
```suggestion
  const auto& ctx = a->GetContext();
  auto num_row_v = Scalar::Make(arrow::MakeScalar(num_row));
  std::shared_ptr<Column> num_row_col;
  RETURN_CYLON_STATUS_IF_FAILED(ctx->GetCommunicator()->Allgather(num_row_v, &num_row_col));
  
  int64_t* vals = std::static_pointer_cast<arrow::Int64Array>(num_row_col->data())->raw_values();
  
  // TODO: it would have been nice, if you could use int64_t* vals, and int64_t num_row_col->length() instead of a vector
  // creating a vector here, copies data again 
  std::vector<int64_t> rows_per_partition(vals, vals + num_row_col->length()); 
```

File: cpp/src/cylon/table.cpp [hunk 2]
```diff
@@ -1513,12 +1520,17 @@ Status DistributedEquals(const std::shared_ptr<cylon::Table> &a,
...
   }
 
-  RETURN_CYLON_STATUS_IF_FAILED(mpi::AllReduce(a->GetContext(),
-                                               &subResult,
-                                               &result,
-                                               1,
-                                               Bool(),
-                                               cylon::net::LAND));
+  auto sub_result_scalar =
+      std::make_shared<Scalar>(std::move(arrow::MakeScalar(int8_t(subResult))));
```
Comment (nirandaperera) [inline cpp/src/cylon/table.cpp:1524]: when you are passing a `shared_ptr` to a constructor (Rvalue), moving is unnecessary. you would only have to move Lvalues. 
```suggestion
  auto sub_result_scalar = std::make_shared<Scalar>(arrow::MakeScalar(int8_t(subResult)));
```

File: cpp/src/cylon/table.cpp [hunk 3]
```diff
@@ -1537,8 +1549,22 @@ Status Repartition(const std::shared_ptr<cylon::Table> &table,
...
+
+  RETURN_CYLON_STATUS_IF_FAILED(
+      table->GetContext()->GetCommunicator()->Allgather(num_row_col,
+                                                        &sizes_cols));
+
+  for (auto col : sizes_cols) {
+    auto temp = std::static_pointer_cast<arrow::Int64Scalar>(
+        col->data()->GetScalar(0).ValueOrDie());
+    sizes.push_back(temp->value);
+  }
```
Comment (nirandaperera) [inline cpp/src/cylon/table.cpp:1567]: same comment as before!

File: cpp/src/cylon/table.cpp [hunk 4]
```diff
@@ -1584,11 +1610,18 @@ Status Repartition(const std::shared_ptr<cylon::Table> &table,
 Status Repartition(const std::shared_ptr<cylon::Table> &table,
                    std::shared_ptr<cylon::Table> *output) {
   int world_size = table->GetContext()->GetWorldSize();
-  std::vector<int64_t> size = {table->Rows()};
-  std::vector<int64_t> sizes;
-  RETURN_CYLON_STATUS_IF_FAILED(mpi::AllGather(table->GetContext(), size, world_size, sizes));
 
-  auto result = DivideRowsEvenly(sizes);
+  auto size =
+      std::make_shared<Scalar>(std::move(arrow::MakeScalar(table->Rows())));
```
Comment (nirandaperera) [inline cpp/src/cylon/table.cpp:1615]:
```suggestion
      std::make_shared<Scalar>(arrow::MakeScalar(table->Rows()));
```

**Review by nirandaperera — CHANGES_REQUESTED** [review]

File: cpp/src/cylon/table.cpp [hunk 5]
```diff
@@ -1469,19 +1467,28 @@ Status Equals(const std::shared_ptr<cylon::Table> &a, const std::shared_ptr<cylo
...
+
+  RETURN_CYLON_STATUS_IF_FAILED(
+      a->GetContext()->GetCommunicator()->Allgather(num_row_scalar, &output));
+
+
+  for (int64_t i = 0; i < output->length(); i++) {
+    auto temp = std::static_pointer_cast<arrow::Int64Scalar>(
+        output->data()->GetScalar(i).ValueOrDie());
+    rows_per_partition.push_back(temp->value);
+  }
```
Comment (nirandaperera) [inline cpp/src/cylon/table.cpp:1491]:
```suggestion
  std::shared_ptr<cylon::Column> output;
  RETURN_CYLON_STATUS_IF_FAILED(
      a->GetContext()->GetCommunicator()->Allgather(num_row_scalar, &output));
  auto * data_ptr = std::static_pointer_cast<arrow::Int64Array>(output->data())->raw_values();

 rows_per_partition.resize(output->length());
 std::copy(data_ptr, data_ptr+output->length(), rows_per_partition.data());
```

File: cpp/test/CMakeLists.txt [hunk 6]
```diff
@@ -65,141 +65,7 @@ endfunction(cylon_run_test)
 #Add tests as follows ...
 # param 1 -- name of the test, param 2 -- number of processes
```
Comment (nirandaperera) [inline cpp/test/CMakeLists.txt:66]: IMPORTANT: Please re-enable these tests!!!

**Review by nirandaperera — CHANGES_REQUESTED** [review]

**Comment by nirandaperera** [comment]
@kaiyingshan is this ready? Can you run a code reformatter on the changed files?

File: cpp/test/partition_test.cpp [hunk 7]
```diff
@@ -101,7 +101,7 @@ TEST_CASE("Partition testing", "[join]") {
   }
 
   SECTION("dist sort test") {
-    status = cylon::DistributedSort(table, 0, output, true, {(uint32_t) WORLD_SZ, (uint64_t) table->Rows()});
+    status = cylon::DistributedSort(table, 0, output, true, {(uint32_t) WORLD_SZ, (uint64_t) table->Rows(), SortOptions::REGULAR_SAMPLE});
```
Comment (nirandaperera) [inline cpp/test/partition_test.cpp:104]: nit: I feel like this is more than 100 chars! :slightly_smiling_face:

**Review by nirandaperera — CHANGES_REQUESTED** [review]
small change request

**Review by nirandaperera — APPROVED** [review]
